FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o lpnfuel .

FROM alpine:3.19
RUN apk add --no-cache tzdata ca-certificates

WORKDIR /app
COPY --from=builder /app/lpnfuel .
COPY db/migrations/ db/migrations/

EXPOSE 8080
CMD ["./lpnfuel"]
